### PR TITLE
celebration sápmi modal for desktop ok

### PR DESCRIPTION
**Pull request by Fagerdahl**
## Pull Request Type
Please check the type of change your PR introduces:
- [x] Feature (a new feature for the project)
- [x] Fix (a bug fix)
- [ ] Chore (updating grunt tasks etc; no production code change)
- [ ] Refactor (refactoring production code)
- [ ] Docs (changes to the documentation)
- [x] Style (formatting, missing semi colons, etc; no production code change)
- [ ] Test (adding missing tests, refactoring tests; no production code change)

## Description
The modal is done with all its info. 
It is also responsive to smaller screens.

## How Has This Been Tested?
Manually tested, no bugs

## Screenshots (if appropriate):
Skärmbild 2024-12-27 140529

MOBILE 
Skärmbild 2024-12-27 140546

What is this and how do I get rid of it without making syntax errors? 
Skärmbild 2024-12-27 140552 
image

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have named this PR according to following naming convention: #[issue-number] PR description

## Additional Information:
I have an ambition to put all the modal information in our JSON resource insted of hardcoded in JS, but that will be a later priority (perhaps for next sprint).

### CODE REVIEW

**Review by AlexCode-dot — COMMENTED** [review]
Well done! The content in the modal is awesome, great info. 
Before merge could you remove: 
- Line 4 and 5 in main.scss
- Line 14 in index.html
These lines was a bug fixed in earlier PR

A tip that you do not have to do, is to create and load all content inside the modal from our Frontpage-content.json file. For an example, this would help if we want to add different languages to our page in the future.

**Comment by Fagerdahl** [comment]
Before merge could you remove:
  * Line 4 and 5 in main.scss
 * Line 14 in index.html

DONE :-) 
 
> A tip that you do not have to do, is to create and load all content inside the modal from our Frontpage-content.json file. For an example, this would help if we want to add different languages to our page in the future.

Thank you for your valuable guidance. I really appreciate it! Working on it and will update soon

**Comment by Fagerdahl** [comment]
Skärmbild 2024-12-27 124355

I commented out this JSON resource since I am not sure if I got enough time to implement it. I am still learning how. But now we have the data in there, in case I figure it out. I will have to move this card but will soon update with breakpoint for smaller screens.

**Comment by Deansie** [comment]
Looks good, well done! 

There are a couple of hings I would like to point out though. Firstly, in the mobile view you could perhaps add some padding to the top and bottom because right now the modal reaches outside the screen. And secondly, should we somehow create a new backlog-item for future sprints to implement a timed function that allows the modal to appear near februari 6th instead of the whole year around?

Other than that you have my approval!

**Review by Deansie — APPROVED** [review]

**Review by AlexCode-dot — APPROVED** [review]
Well done, looks great and I love the animations. About the issue you posted:
Screenshot 2024-12-27 at 14 52 23
You only need to remove the " after {data.details}

You can merge when you are ready :)

**Comment by Fagerdahl** [comment]
Skärmbild 2024-12-27 180151
I ma
Skärmbild 2024-12-27 180131
I did some improvements and made it visually more appealing. 

I am gonna look up how to make it visible around a specific timeframe around 6th of feb if you think it is important. Could it be in the next sprint? 

I also changed PX to responsive units since it is best practice.

**Comment by Deansie** [comment]
> Skärmbild 2024-12-27 180151 I ma Skärmbild 2024-12-27 180131 I did some improvements and made it visually more appealing.
> 
> I am gonna look up how to make it visible around a specific timeframe around 6th of feb if you think it is important. Could it be in the next sprint?
> 
> I also changed PX to responsive units since it is best practice.
> 
> PS) Screens smaller than 350px = Parkour

Looks brilliant, well done! I agree that we should wait until next sprint to implement the specific timeframe for the modal to appear.

**Pull request merged**
