### PR TITLE
#49 4.5 Footer: Style

### PR DESCRIPTION
**Pull request by Kalu32k**
## Pull Request Type
Please check the type of change your PR introduces:
- [X] Feature (a new feature for the project)
- [X] Fix (a bug fix)
- [ ] Chore (updating grunt tasks etc; no production code change)
- [ ] Refactor (refactoring production code)
- [ ] Docs (changes to the documentation)
- [X] Style (formatting, missing semi colons, etc; no production code change)
- [ ] Test (adding missing tests, refactoring tests; no production code change)

## Description
[Provide a detailed description of the changes in this pull request]

- Styling to the footer to look like the design and reactive to mobile screens.
- Small fix to the background so it wont go white when scrolling down.
- Small fix to the body so it matches the padding of the header and footer.
- Adding some lost text from main.js in the footer.

## Motivation and Context
[Why is this change required? What problem does it solve?]
Styling to the footer so it looks good
It fixes the background and body in the index.

## How Has This Been Tested?
[Describe the tests that you ran to verify your changes]

- Did some testing in live share.

## Screenshots (if appropriate):
[Add screenshots here]
image
Desktop view
image
Mobile view
## Checklist:
- [ ] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [X] I have named this PR according to following naming convention: #[issue-number] PR description

## Additional Information:
[Add any other information about the PR here]
branch copy paste for testing: git checkout footer-contacts
## Related Issues:
[Link any related issues here]

### CODE REVIEW

**Comment by Hungryhippoafk** [comment]
Excellent work! 
Looks good on both desktop and mobile version!
Can´t spot anything wrong with the code.

**Review by Patseroni — COMMENTED** [review]
Both design and code looks good!

**Review by Fagerdahl — APPROVED** [review]
👍

**Comment by Kalu32k** [comment]
Did a pull to update the branch before merge to main

**Pull request merged**
